name: Release Extension

on:
  workflow_run:
    workflows: ["Build Extension"]
    types:
      - completed

jobs:
  deploy_test:
    name: Test
    uses: ./.github/workflows/release.job.yml
    with:
      env_suffix: test
    secrets:
      azure_devops_token: ${{ secrets.AZURE_DEVOPS_TOKEN }}

  deploy_prod:
    name: Production
    needs: deploy_test
    uses: ./.github/workflows/release.job.yml
    with:
      env_suffix: prod
    secrets:
      azure_devops_token: ${{ secrets.AZURE_DEVOPS_TOKEN }}