name: Release Extension

on:
  workflow_run:
    workflows: ["Build Extension"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master' }}
    environment: development

    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: banner-settings-extension
          path: ./artifacts
          search_artifacts: true

      - name: Install TFX CLI
        run: npm install -g tfx-cli

      - name: Authenticate and Publish
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        run: |
          tfx extension publish --manifest-globs vss-extension.json --service-url https://dev.azure.com/myorg --token $AZURE_DEVOPS_EXT_PAT
